//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Infrastructure.Identity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configurations
    {
        public int Id { get; set; }
        public int ContactInfoId { get; set; }
        public string BusinessName { get; set; }
        public string OwnerName { get; set; }
        public string RucNumber { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
    }
}
