//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Infrastructure.Identity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HardwareStoreEntities : DbContext
    {
        public HardwareStoreEntities()
            : base("name=HardwareStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Configurations> Configurations { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<CurrencyExchange> CurrencyExchange { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DetailProductStocks> DetailProductStocks { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<ForeignCurrencies> ForeignCurrencies { get; set; }
        public virtual DbSet<LocalCurrencies> LocalCurrencies { get; set; }
        public virtual DbSet<MaterialsTypes> MaterialsTypes { get; set; }
        public virtual DbSet<MeasureUnits> MeasureUnits { get; set; }
        public virtual DbSet<PendingTransfers> PendingTransfers { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<ProductDetails> ProductDetails { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductStocks> ProductStocks { get; set; }
        public virtual DbSet<ProductTransfers> ProductTransfers { get; set; }
        public virtual DbSet<PurchaseDetails> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseInvoices> PurchaseInvoices { get; set; }
        public virtual DbSet<RemovedProducts> RemovedProducts { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SalesDetails> SalesDetails { get; set; }
        public virtual DbSet<SalesInvoices> SalesInvoices { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<TransfersDetails> TransfersDetails { get; set; }
        public virtual DbSet<UnitConversion> UnitConversion { get; set; }
        public virtual DbSet<UnitTypes> UnitTypes { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
