//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareStore.Infrastructure.Identity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemovedProducts
    {
        public int Id { get; set; }
        public int ProductStocksId { get; set; }
        public string LotNumber { get; set; }
        public string StocksDetailCode { get; set; }
        public int UnitQuantity { get; set; }
        public double ConversionQuantity { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ProductStocks ProductStocks { get; set; }
    }
}
